theme = "onedark"

[editor]
mouse = false
middle-click-paste = false
cursorline = true
gutters = ["line-numbers", "diff"]
completion-replace = true
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
