theme = "onedark+"

[editor]
mouse = false
middle-click-paste = false
cursorline = true
auto-format = false
completion-replace = true
color-modes = true
preview-completion-insert = true
undercurl = true
insert-final-newline = true
rulers = [80, 120]
popup-border = "popup"

[editor.smart-tab]
enable = false

[editor.statusline]
left = ["mode", "read-only-indicator", "file-name", "file-modification-indicator", "version-control"]
center = []
right = ["selections" ,"spinner", "file-type"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-inlay-hints = false
display-messages = true
auto-signature-help = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "┆"

[editor.gutters]
layout = ["line-numbers", "spacer", "diff", "spacer"]
line-numbers.min-width = 2

[editor.soft-wrap]
enable = true
max-wrap = 40


[keys.normal]
esc = "keep_primary_selection"
C-s = ":w"
C-x = ":buffer-close"
C-q = "wclose"
C-r = ":reload"
C-a = "select_all"
C-down = "copy_selection_on_next_line"
C-up =   "copy_selection_on_prev_line"
l = "extend_line_below"
d = "delete_selection_noyank"
x = "delete_selection"
H = "hover"
c = "change_selection_noyank"
K = "select_regex"
k = ["search_selection", "select_mode"]
S = "split_selection"
s = "split_selection_on_newline"
C-right = "move_next_word_end"
C-left = "move_prev_word_start"
# BUFFERS
tab = "goto_next_buffer"
S-tab = "goto_previous_buffer"
# DISABLE DEFUALTS
C-w = "no_op"
C = "no_op"
C-c = "no_op"

[keys.normal.space]
F = "file_picker_in_current_buffer_directory"
s = ":format"
b = "no_op"
j = "no_op"
"/" = "no_op"
S = "no_op"
D = "no_op"
c = "toggle_comments"

[keys.normal.space.f]
f = "file_picker"
b = "buffer_picker"
s = "symbol_picker"
j = "jumplist_picker"
w = "global_search"

[keys.normal.space.d]
n = "goto_next_diag"
p = "goto_prev_diag"
a = "workspace_diagnostics_picker"

[keys.normal.space.h]
r = ":reset-diff-change"
n = "goto_next_change"
p = "goto_prev_change"

[keys.insert]
C-s = [":w", "normal_mode"]
C-right = "move_next_word_end"
C-left = "move_prev_word_start"
C-space = "completion"

[keys.select]
c = "change_selection_noyank"
d = "delete_selection_noyank"
x = "delete_selection"
