[[language]]
name = "typescript"
language-servers = [
  { name = "efm", only-features = [ "diagnostics", "format" ] }, 
  "typescript-language-server",
]

[[language]]
name = "tsx"
language-servers = [
  { name = "efm", only-features = [ "diagnostics", "format" ] }, 
  "typescript-language-server",
]

[[language]]
name = "javascript"
language-servers = [
  { name = "efm", only-features = [ "diagnostics", "format" ] }, 
  "typescript-language-server",
]

[[language]]
name = "jsx"
language-servers = [
  {name = "eslint", only-features = ["diagnostics"]},  
  "typescript-language-server",
]


[language-server.typescript-language-server]
command = "npx"
args = ["typescript-language-server", "--stdio"]

[language-server.svelteserver]
command = "npx"
args = ["svelte-language-server", "--stdio"]

[language-server.vscode-css-language-server]
command = "npx"
args = ["--package=vscode-langservers-extracted", "--", "vscode-css-language-server", "--stdio"]

[language-server.vscode-html-language-server]
command = "npx"
args = ["--package=vscode-langservers-extracted", "--", "vscode-html-language-server", "--stdio"]

[language-server.vscode-json-language-server]
command = "npx"
args = ["--package=vscode-langservers-extracted", "--", "vscode-json-language-server", "--stdio"]

[language-server.prisma-language-server]
command = "npx"
args = ["prisma-language-server", "--stdio"]

[language-server.tailwindcss-language-server]
command = "npx"
args = ["tailwindcss-language-server", "--stdio"]

[language-server.unocss-language-server]
command = "npx"
args = ["unocss-language-server", "--stdio"]

[language-server.efm]
command = "efm-langserver"
