[[language]]
name = "typescript"
language-servers = [
  { name = "efm", only-features = [ "diagnostics", "format" ] }, 
  "typescript-language-server",
]

[[language]]
name = "tsx"
language-servers = [
  { name = "efm", only-features = [ "diagnostics", "format" ] }, 
  "typescript-language-server",
]

[[language]]
name = "javascript"
language-servers = [
  { name = "efm", only-features = [ "diagnostics", "format" ] }, 
  "typescript-language-server",
]

[[language]]
name = "jsx"
language-servers = [
  { name = "efm", only-features = [ "diagnostics", "format" ] }, 
  "typescript-language-server",
]

[language-server.yaml-language-server.config.yaml]
schemaStore = {enable = true}

[language-server.efm]
command = "efm-langserver"

[language-server.vscode-json-language-server.config.json]
validate = {enable = true}
